version: '3.8'

services:
  app1:
    build: ./app1
    container_name: app1

  app2:
    build: ./app2
    container_name: app2

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

